#!/bin/bash
# ② 上下文层 · SessionStart hook：注入 feature 索引 + 据 repos.tsv 渲染涉及仓清单 + 物化各仓 CLAUDE.md
#
# 真实环境：锚定仓(frameworks/base→native→…)读当前 git 分支 → cat _index.md 注入 →
#   据 repos.tsv 渲染涉及仓清单一并注入（repos.tsv 是仓清单单一事实源，_index 不复列）→
#   为「有约定文件」的涉及仓在仓根物化 CLAUDE.md，写各仓 .git/info/exclude 隔离（编辑该仓时按需加载）。
# DEMO：无真实 repo 树，分支读 CURRENT_FEATURE；占位仓目录非独立 git 仓，exclude 那步降级为打印说明，
#   生成的各仓 CLAUDE.md 由顶层 .gitignore 忽略。
set -euo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"

# ---- 读掉 stdin 的 JSON（真实 hook 会用到 cwd；demo 里读掉即可，避免管道阻塞） ----
cat >/dev/null 2>&1 || true

# ---- 当前 feature：只认有独立 .git 的锚定仓（避免 demo 占位目录落顶层 git 仓内误读 main），否则回退 CURRENT_FEATURE ----
feature=""
for repo in frameworks/base frameworks/native system/core; do
  if [ ! -e "$ROOT/$repo/.git" ]; then continue; fi
  if b="$(git -C "$ROOT/$repo" rev-parse --abbrev-ref HEAD 2>/dev/null)"; then feature="$b"; break; fi
done
if [ -z "$feature" ] && [ -f "$ROOT/CURRENT_FEATURE" ]; then
  feature="$(tr -d '[:space:]' < "$ROOT/CURRENT_FEATURE")"
fi

index="$ROOT/features/$feature/_index.md"
if [ -z "$feature" ] || [ ! -f "$index" ]; then
  echo "[load-feature] 未找到当前 feature 的索引（feature='${feature:-?}'），跳过注入。" >&2
  exit 0
fi

# ---- 记录快照，供 UserPromptSubmit 的漂移检测比对 ----
echo "$feature" > "${TMPDIR:-/tmp}/.aosp-harness-demo.feature-snapshot"

# ---- ② 第一段：注入 _index.md（指针粒度：目标 + 指向 repos.tsv + 验证入口） ----
echo "===== [SessionStart 注入] 当前 feature = $feature ====="
cat "$index"

# ---- ② 第二段：据 repos.tsv 一次遍历 —— 渲染涉及仓清单注入 + 物化各仓 CLAUDE.md ----
repolist="$ROOT/features/$feature/repos.tsv"
featdir="$ROOT/features/$feature"
if [ ! -f "$repolist" ]; then exit 0; fi

render=""
count=0
demo_note=0
while read -r repo conv tags desc || [ -n "$repo" ]; do
  case "$repo" in ''|'#'*) continue;; esac

  # (a) 渲染涉及仓清单行（清单事实源在 repos.tsv，此处仅按行渲染注入）
  tagd="-"; case ",$tags," in *,compdb,*) tagd="compdb";; esac
  convd="$conv"; if [ "$conv" = "-" ]; then convd="(无独立约定，走 skill)"; fi
  line=$(printf '  %-24s [%-6s] %s' "$repo" "$tagd" "$convd")
  render="${render}${line}
"

  # (b) 物化 CLAUDE.md（仅「有单仓约定文件」且仓目录存在的仓）
  if [ "$conv" = "-" ]; then continue; fi
  convfile="$featdir/$conv"
  repodir="$ROOT/$repo"
  if [ ! -f "$convfile" ]; then continue; fi
  if [ ! -d "$repodir" ]; then continue; fi
  {
    echo "<!-- AUTO-GENERATED by .claude/hooks/load-feature.sh — DO NOT EDIT（单一事实源 features/$feature/$conv） -->"
    echo
    cat "$convfile"
  } > "$repodir/CLAUDE.md"
  count=$((count + 1))
  if [ -e "$repodir/.git" ]; then
    excl="$(git -C "$repodir" rev-parse --git-path info/exclude 2>/dev/null || echo .git/info/exclude)"
    case "$excl" in /*) : ;; *) excl="$repodir/$excl";; esac
    mkdir -p "$(dirname "$excl")" 2>/dev/null || true
    grep -qxF CLAUDE.md "$excl" 2>/dev/null || echo CLAUDE.md >> "$excl"
  else
    demo_note=1
  fi
done < "$repolist"

# 注入涉及仓清单（紧跟 _index，构成 agent 睁眼第一屏；据 repos.tsv 现渲染，无第二份清单）
echo
echo "## 涉及仓（据 repos.tsv —— 仓清单单一事实源；不在清单里的仓默认不动）"
printf '%s' "$render"

echo "[load-feature] 已物化 $count 仓 CLAUDE.md（编辑该仓文件时 Claude Code 按需加载该仓约定）"
if [ "$demo_note" = "1" ]; then
  echo "[load-feature] (demo) 各仓非独立 git 仓：真实环境这些 CLAUDE.md 会写入各仓 .git/info/exclude 隔离、不进 gerrit"
fi
