#!/bin/bash
# ② 上下文层 · SessionStart hook：按当前分支注入 feature 索引 + 物化各仓 CLAUDE.md
#
# 真实环境：从 stdin JSON 拿 cwd → 到锚定仓(frameworks/base→native→…)读当前 git 分支
#   → cat features/<分支>/_index.md 到 stdout（Claude Code 注入为会话上下文）
#   → 再按 features/<分支>/repos.tsv 为每个「有约定文件」的涉及仓在其仓根物化 CLAUDE.md，
#     并写入该仓 .git/info/exclude 使其对 git 隐身、不进 gerrit
#     （编辑该仓文件时 Claude Code 会按需自动加载这份 CLAUDE.md）。
# DEMO：无真实 repo 树，分支读 CURRENT_FEATURE；frameworks/base 等是轻量占位目录（非独立 git 仓），
#   物化照做，但 exclude 那步降级为打印说明（真实环境才写 .git/info/exclude），生成物由顶层 .gitignore 忽略。
set -euo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"

# ---- 读掉 stdin 的 JSON（真实 hook 会用到 cwd；demo 里读掉即可，避免管道阻塞） ----
cat >/dev/null 2>&1 || true

# ---- 确定当前 feature（= repo 分支名） ----
# 只认「有独立 .git 的锚定仓」→ 避免 demo 里占位目录落在顶层 git 仓内、误读成顶层分支。
feature=""
for repo in frameworks/base frameworks/native system/core; do
  if [ ! -e "$ROOT/$repo/.git" ]; then continue; fi
  if b="$(git -C "$ROOT/$repo" rev-parse --abbrev-ref HEAD 2>/dev/null)"; then
    feature="$b"; break
  fi
done
# DEMO 回退：读 CURRENT_FEATURE 文件
if [ -z "$feature" ] && [ -f "$ROOT/CURRENT_FEATURE" ]; then
  feature="$(tr -d '[:space:]' < "$ROOT/CURRENT_FEATURE")"
fi

index="$ROOT/features/$feature/_index.md"
if [ -z "$feature" ] || [ ! -f "$index" ]; then
  echo "[load-feature] 未找到当前 feature 的索引（feature='${feature:-?}'），跳过注入。" >&2
  exit 0
fi

# ---- 记录快照，供 UserPromptSubmit 的漂移检测比对 ----
echo "$feature" > "${TMPDIR:-/tmp}/.aosp-harness-demo.feature-snapshot"

# ---- ② 第一段：把索引打印到 stdout（Claude Code 注入为会话上下文） ----
echo "===== [SessionStart 注入] 当前 feature = $feature ====="
cat "$index"

# ---- ② 第二段：按 repos.tsv 为各涉及仓物化 CLAUDE.md ----
repolist="$ROOT/features/$feature/repos.tsv"
featdir="$ROOT/features/$feature"
if [ ! -f "$repolist" ]; then exit 0; fi

count=0
demo_note=0
while read -r repo conv tags desc || [ -n "$repo" ]; do
  case "$repo" in ''|'#'*) continue;; esac
  if [ "$conv" = "-" ]; then continue; fi          # 无独立约定文件（走 skill）的仓不物化
  convfile="$featdir/$conv"
  repodir="$ROOT/$repo"
  if [ ! -f "$convfile" ]; then continue; fi
  if [ ! -d "$repodir" ]; then continue; fi         # demo 只为造了占位目录的仓物化
  {
    echo "<!-- AUTO-GENERATED by .claude/hooks/load-feature.sh — DO NOT EDIT（单一事实源 features/$feature/$conv） -->"
    echo
    cat "$convfile"
  } > "$repodir/CLAUDE.md"
  count=$((count + 1))
  if [ -e "$repodir/.git" ]; then
    # 真实环境：各仓是独立 git 仓 → 写入 .git/info/exclude 隔离，不进 gerrit
    excl="$(git -C "$repodir" rev-parse --git-path info/exclude 2>/dev/null || echo .git/info/exclude)"
    case "$excl" in /*) : ;; *) excl="$repodir/$excl";; esac
    mkdir -p "$(dirname "$excl")" 2>/dev/null || true
    grep -qxF CLAUDE.md "$excl" 2>/dev/null || echo CLAUDE.md >> "$excl"
  else
    demo_note=1
  fi
done < "$repolist"

echo "[load-feature] 已物化 $count 仓 CLAUDE.md（编辑该仓文件时 Claude Code 按需加载该仓约定）"
if [ "$demo_note" = "1" ]; then
  echo "[load-feature] (demo) 各仓非独立 git 仓：真实环境这些 CLAUDE.md 会写入各仓 .git/info/exclude 隔离、不进 gerrit"
fi
